spring:
  datasource:
    url: jdbc:mysql://${MYSQL_HOST:localhost}:3306/casa_do_codigo?createDatabaseIfNotExist=true
    username: root
    password: mariadb123

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true